name: lcbsi-ai
channels:
  - apple
  - pytorch-nightly
  - conda-forge
dependencies:
  - monai
  - python=3.9
  - pytorch
  - tensorflow-deps
  - pytorch-lightning
  - torchvision
  - dash-bootstrap-components
  - dash-core-components
  - dash-html-components
  - dash-table
  - dash
  - dash-daq
  - flask-compress
  - flask
  - numpy
  - plotly
  - pip
  - pip:
    - tensorflow-metal==0.5.0
    - tensorflow-macos==2.9
    - ipywidgets==7.7.2
    - pillow
    - seaborn
    - importlib-metadata==4.12.0
    - opencv-python==4.6.0.66
    - ipython
    - psutil
    - torchstain==1.2.0
    - scikit-image
    - black
    - pytest
    - roboflow
    - wandb
    - isort
    - scikit-learn
    - huggingface-hub
    - transformers
    - datasets
